---
title: "GaoSciAdv2025Figs"
author: "Winston Huang"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(Seurat)
library(openxlsx)
library(clusterProfiler)
library(org.Hs.eg.db)
library(fgsea)
library(tidyverse)
library(ggsignif)
library(RColorBrewer)
library(EPIC)
```

# Input Data
```{r}
so <- readRDS('data/GaoSciAdv2025.rds') # so
```

# Output Folder
```{r}
proj_name <- 'GaoSciAdv2025Figs'
parent_folder <- getwd()
dir.create(sprintf('%s/%s', parent_folder, proj_name))
folder_path <- sprintf('%s/%s', parent_folder, proj_name)

colors_orig <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "cyan", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)
```

# Figure 1A
```{r}
# Load data
deg <- read.xlsx('data/Choi2014_Phil_Post.vs.Before_AllGenes.xlsx', cols = 1:10, sheet = 'p<0.05')
original_gene_list <- deg$log2FC_Post.vs.Before
names(original_gene_list) <- deg$Entrez_Gene_ID
gene_list <- na.omit(original_gene_list)
gene_list <- sort(gene_list, decreasing = FALSE)
gene_list <- gene_list[!duplicated(names(gene_list))]

# Load geneset
geneset <- read.xlsx('data/harmonizome_fibroblast_geneset.xlsx', colNames = F)

geneset_entrez <- bitr(geneID = geneset$X1, 'SYMBOL', 'ENTREZID', OrgDb = org.Hs.eg.db)

# geneset_list <- intersect(names(gene_list), geneset_entrez$ENTREZID)
geneset_list <- list('Harmonizome_FIBROBLAST' = geneset_entrez$ENTREZID)

gsea_results <- fgsea(pathways = geneset_list, stats = gene_list, scoreType = 'std', minSize = 10, maxSize = 500)

plotGseaTable(geneset_list[1], gene_list, gsea_results, gseaParam = 1)
plotEnrichment(
  pathway = geneset_list[[1]],
  stats = gene_list,
  gseaParam = 1,
  ticksSize = 0.2
) + labs(
  title = paste0(
    gsea_results$pathway,
    '\nNES:',
    round(gsea_results$NES, 2),
    '\nAdjusted p-value:',
    ifelse(gsea_results$padj < 0.0001, format(gsea_results$padj, scientific = T, digits = 3), round(gsea_results$padj, 3))
  )
) + theme_classic() +
  scale_y_continuous('Enrichment Score (ES)') +
  scale_x_continuous('Rank', breaks = seq(0, 7000, 1000))
```

# Figure 1G/1H/1I
```{r}
custom_genes = c('ACTA2', 'IL6')

DotPlot(so, group.by = 'FB_Annotation', features = custom_genes, scale = T, scale.by = 'size') + 
  labs(y = "", x = "") +
  theme(legend.text = element_text(size = 8), 
        legend.direction = 'vertical',
        legend.position = 'right',
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(size = 10, face = 'bold'), 
        axis.text = element_text(size = 5)) + 
  scale_color_gradient2(low = 'blue', mid = 'grey90', high = 'red', midpoint = 0) + 
  scale_y_discrete(limits = rev(levels(so$FB_Annotation)))

DimPlot(so, reduction = 'tsne', group.by = 'FB_Annotation', cols = colors_orig, label = T, repel = T, raster = F, pt.size = 2, label.size = 6, label.box = T, combine = T) + NoLegend() + scale_fill_manual(values = c('transparent', 'transparent', 'transparent', 'transparent', 'transparent', 'transparent')) + theme(aspect.ratio = 1)

custom_genes <- c('COL10A1', 'MMP11', 'INHBA', 'MYH11', 'ACTA2', 'RGS5', 'MCAM', 'CCL2', 'CCL19', 'IL6', 'CXCL2', 'CXCL12', 'CXCL14', 'C3', 'PDPN', 'PDGFRA', 'SLC14A1', 'WNT5A', 'MKI67', 'CDK1')
DotPlot(so, group.by = 'FB_Annotation', features = custom_genes, scale = T, scale.by = 'size') + 
  ylab('CAF Clusters') +
  theme(legend.text = element_text(size = 8), 
        legend.direction = 'vertical',
        legend.position = 'right',
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(size = 10, face = 'bold'), 
        axis.text = element_text(size = 5)) + 
  scale_color_gradient2(low = 'blue', mid = 'grey90', high = 'red') + 
  scale_y_discrete(limits = levels(so$FB_Annotation)) +
  scale_x_discrete(limits = rev(custom_genes)) +
  coord_flip() +
  ggtitle("")
```

# Figure 1L
```{r}
caf_prop <- readRDS('data/choi_caf_prop.rds') # top 20 genes with padj < 0.05 and log2FC > 1 

for (caf in colnames(caf_prop)[1:4]) {
  pre <- caf_prop[, caf][1:20]  
  post <- caf_prop[, caf][21:40]

  results_wt <- wilcox.test(pre, post, paired = T)
  
  results_wt_signif <- cut(results_wt$p.value, 
                           breaks = c(0, 0.0001, 0.001, 0.01, 0.05, 1), 
                           labels = c('****', '***', '**', '*', 'ns'), 
                           right = TRUE)
  
  plot <- ggplot(data = caf_prop, mapping = aes(x = group, y = caf_prop[, caf], fill = group)) +
    geom_boxplot(show.legend = FALSE, outliers = TRUE, staplewidth = 0.2) +
    labs(title = sprintf('Choi-EPIC \n%s', caf), x = 'Patient Group', y = 'Fraction') +
    scale_x_discrete() +
    scale_y_continuous() +
    scale_fill_manual(values = c(brewer.pal(9, 'Set1')[2], brewer.pal(9, 'Set1')[1])) +
    theme_minimal() +
    theme(
      text = element_text(size = 10), 
      title = element_text(size = 12, hjust = 0.5, vjust = 0.5), 
      axis.text.x.bottom = element_text(angle = 45, hjust = 1)
    )
  
  plot <- plot + geom_signif(
    comparisons = list(c("Pre", "Post")),  
    y_position = max(caf_prop[, caf]) * 1.1,  
    annotations = as.character(results_wt_signif),  
    tip_length = 0.02, size = 1, textsize = 3, vjust = 0.3
  )

  print(plot)
}
```

# Figure S1C/S1D
```{r}
all.markers <- FindAllMarkers(so, features = VariableFeatures(so), group.by = 'FB_Annotation')
all.markers$cluster <- factor(all.markers$cluster, labels = levels(so$FB_Annotation))
all.markers <- all.markers[all.markers$p_val_adj < 0.05 & all.markers$avg_log2FC > 1,]
all.markers.ordered <- all.markers %>% group_by(cluster) %>% arrange(cluster, desc(avg_log2FC))
top <- top_n(all.markers.ordered, 20, avg_log2FC)
DoHeatmap(object = so, features = top$gene, group.by = 'FB_Annotation', combine = T, label = T, raster = 1000, group.colors = colors_orig, size = 8, angle = 45, hjust = 0) + 
  theme(aspect.ratio = 3, axis.text.y = element_text(size = 15)) + 
  # scale_fill_gradient2(low = 'navy', mid = 'white', high = 'darkred') + 
  NoLegend()

cols <- c('COL1A1', 'COL1A2', 'COL3A1')
plot_list <- list()
for (col in cols){
  plot_list[[col]] <- VlnPlot(so, group.by = 'FB_Annotation', features = col, cols = colors_orig, ncol = 1, pt.size = 0) +
    labs(y = col) +
    theme(
      axis.text.y = element_text(face = "bold.italic")
    ) +
    ggtitle("") +
    NoLegend()
}

VlnPlot(so, assay = 'integrated', group.by = 'FB_Annotation', features = cols, cols = colors_orig, pt.size = 0, stack = T, fill.by = "ident", flip = T) + 
  labs(x = "", y = "") +
  scale_y_continuous(limits = c(-1, 7), breaks = seq(0, 6, 2)) +
  NoLegend()
```

# Figure S2A
```{r}
so_psf <- readRDS("data/so_with_peri.rds")

pericyte_markers = c('KCNJ8', 'ABCC9', 'HIGD1B', 'RGS5', 'NDUFA4L2', 'CD248', 'CSPG4', 'NOTCH3', 'MCAM')
DotPlot(so_psf, features = pericyte_markers, assay = 'integrated', group.by = 'FB_Annotation', scale = T, scale.by = 'size') + 
  labs(x = '', y = 'Cell Types') +
  theme(legend.text = element_text(size = 8), 
        legend.direction = 'vertical',
        legend.position = 'right',
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 10),
        axis.text = element_text(size = 5)) + 
  scale_y_discrete(limits = rev(levels(so_psf$FB_Annotation))) +
  scale_color_gradient2(low = 'blue', mid = 'white', high = 'red') 
```
